name: C++ Build and Commit Output

on:
  push:
    branches:
      - master  # Upewnij się, że używasz poprawnej gałęzi
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest  # Używamy Windows jako środowiska

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up MinGW (GCC) compiler
        run: |
          choco install mingw  # Instalujemy MinGW, który zawiera kompilator GCC

      - name: Compile the code
        run: |
          g++ -o my_program.exe main.cpp  # Kompiluje plik C++ do pliku .exe

      - name: Create a result file
        run: |
          echo "Kompilacja zakończona!" > result.txt  # Tworzymy plik tekstowy

      - name: Commit and push the result file
        env:
          GH_TOKEN: ${{ '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' }} 
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add my_program.exe result.txt  # Dodajemy plik .exe oraz result.txt
          git commit -m "Add .exe file after build"
          git push https://github.com/0Szogun0/wwds.git HEAD:master  # Wypychamy do repozytorium
