name: C++ Build and Commit Output

on:
  push:
    branches:
      - master  # Zmieniamy 'main' na 'master'
  pull_request:
    branches:
      - master  # Zmieniamy 'main' na 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      - name: Compile the code
        run: |
          g++ -o my_program main.cpp  # Kompiluje plik C++ i tworzy plik 'my_program'

      - name: Create a result file
        run: |
          echo "Kompilacja zakończona!" > result.txt  # Tworzy plik 'result.txt'

      - name: Commit and push the result file
        env:
          GH_TOKEN: ${{ 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 }}  # Token jako sekret
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add result.txt
          git commit -m "Add result file after build"
          git push https://github.com/0Szogun0/wwds.git HEAD:master  # Używamy tokenu do wypchnięcia
