name: C++ Build

on:
  push:
    branches:
      - main  # Lub inna gałąź, na której chcesz uruchomić kompilację
  pull_request:
    branches:
      - main  # Lub inna gałąź, na której chcesz uruchomić kompilację

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up C++ environment
        uses: actions/setup-cpp@v1
        with:
          compiler: g++  # Możesz użyć innego kompilatora, np. clang++

      - name: Install dependencies (jeśli potrzebne)
        run: |
          sudo apt update
          sudo apt install -y build-essential

      - name: Compile the code
        run: |
          g++ -o my_program main.cpp  # Zmień zgodnie z nazwą swojego pliku i programu

      - name: Run tests (jeśli masz testy)
        run: ./my_program  # Uruchomienie programu po kompilacji
