name: C++ Build and Commit Output

on:
  push:
    branches:
      - master  # Użyj odpowiedniej gałęzi, jeśli masz inną
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      - name: Compile the code
        run: |
          g++ -o my_program main.cpp  # Kompiluje plik C++ i tworzy plik 'my_program'

      - name: Create a result file
        run: |
          echo "Kompilacja zakończona!" > result.txt  # Tworzy plik 'result.txt'

      - name: Commit and push the result file
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add result.txt
          git commit -m "Add result file after build"
          git push origin main  # Zatwierdza i wypycha plik 'result.txt' do repozytorium

