name: C++ Build

on:
  push:
    branches:
      - master  # Użyj tej gałęzi, na której chcesz uruchomić workflow
  pull_request:
    branches:
      - master  # Lub zmień na swoją główną gałąź

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      - name: Compile the code
        run: |
          g++ -o my_program main.cpp  # Zmienna na inną nazwę pliku, jeśli jest inna

      - name: Run program
        run: |
          ./my_program
